### ISSUE TITLE
cannot run sudo

### ISSUE THREAD

**Issue by rapidhere** [sedabull/quantum-shell#15]
when i use sudo in the shell, it just get

```
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or  an NFS file system without root privileges?
```

anyway, this is a amazing plugin for atom, but is there any workaround to solve this problem?

**Comment by hoosierhobbyist** [comment]
@rapidhere, thank you for your interest in quantum-shell! To answer your question, changing users in `quantum-shell` is not currently supported. However, there is a potential workaround. If you launch Atom from the command line with root privileges something like this:

```
sudo atom .
```

then you will have root privileges in `quantum-shell`.

BE WARNED HOWEVER...this is extremely dangerous. I do not recommend doing this unless it is absolutely nessecary as it will grant all of Atom, including every other plugin, root privileges as well. You will need to completely close down Atom and restart it in order to return to normal user status.

Also, I'm sure you realize this, but I'll say it anyway. This is a rather ridiculous workaround, since you have to go to the command line anyway to launch Atom with sudo, you might as well just do whatever it is you need to do while you're there. If in the future, I come up with a more proper workaround, I'll be sure to comment here to let you know. And again, thank you for your interest. I truly appreciate it :smiley:

**Comment by rapidhere** [comment]
well, i got it, thx

**Comment by hoosierhobbyist** [comment]
glad to hear it :smile:
